version: '3.8'

services:
  gateway-service:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    image: lujol/gateway-service:v2

  discovery-service:
    build:
      context: ./Discovery     
      dockerfile: Dockerfile
    image: lujol/discovery-service:v2

  customerservice-service:
    build:
      context: ./CostomerService      
      dockerfile: Dockerfile
    image:  lujol/customerservice-service:v3

  order-service:
    build:
      context: ./Order              
      dockerfile: Dockerfile
    image: lujol/order-service:v3

  product-service:
    build:
      context: ./Product            
      dockerfile: Dockerfile
    image: lujol/product-service:v3

  user-service:
    build:
      context: ./User            
      dockerfile: Dockerfile
    image: lujol/user-service:v3