spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://LetsCos.iptime.org:3306/GutJJeu
    username: LetsCo
    password: /9jGamz9ub3rdMG*

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    # 유레카 서버에 나를 등록하지 않음
    register-with-eureka: false
    # 유레카 서버로부터 다른 서비스 목록을 가져오지 않음
    fetch-registry: false