name: 주문 서비스 CI 스크립트

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "Order/**"

jobs:
  execute-test:
    uses: ./.github/workflows/ci-workflow.yml
    secrets: inherit
    with:
      service-name: Order
